teams = (
    "Tottenham",
    "Fulham",
    "Man United",
    "Nott'm Forest",
    "Wolves",
    "Chelsea",
    "Liverpool",
    "Man City",
    "Everton",
    "Bournemouth",
    "Leicester",
    "Arsenal",
    "Newcastle",
    "Crystal Palace",
    "West Ham",
    "Aston Villa",
    "Southampton",
    "Leeds",
    "Brighton",
    "Brentford",
)